#!/usr/bin/env python3
"""Generate a findability catalog of the play library.

Scans data/plays/ and data/play-families/ and writes data/plays/CATALOG.md —
a grouped index so plays are findable without a directory refactor. Plays stay
flat on disk; this file is the map.

Groups:
  - Disguise families (base + companions)
  - Plays by formation
  - Un-familied plays (base plays in no family)

Right-handed mirror plays (`*-left.yaml`) are auto-generated flips; they are
counted but not listed individually — each base play is marked (+mirror) if
its mirror exists.

Run from the repo root:
    python3 tools/play-catalog/generate.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
PLAYS_DIR = REPO_ROOT / "data" / "plays"
FAMILIES_DIR = REPO_ROOT / "data" / "play-families"
OUT_PATH = PLAYS_DIR / "CATALOG.md"


def _is_mirror(stem: str) -> bool:
    return stem.endswith("-left")


def main() -> None:
    all_stems = {p.stem for p in PLAYS_DIR.glob("*.yaml")}
    base_stems = sorted(s for s in all_stems if not _is_mirror(s))
    mirror_stems = {s for s in all_stems if _is_mirror(s)}

    plays: dict[str, dict] = {}
    for stem in base_stems:
        plays[stem] = yaml.safe_load((PLAYS_DIR / f"{stem}.yaml").read_text())

    families = []
    for fp in sorted(FAMILIES_DIR.glob("*.yaml")):
        families.append(yaml.safe_load(fp.read_text()))

    # play_id -> list of family_ids it belongs to (base or companion)
    play_families: dict[str, list[str]] = {}
    familied: set[str] = set()
    for fam in families:
        fid = fam["family_id"]
        members = [fam["base_play_id"]] + list(fam.get("companion_play_ids") or [])
        for m in members:
            play_families.setdefault(m, []).append(fid)
            familied.add(m)

    # group base plays by formation
    by_formation: dict[str, list[str]] = {}
    for stem, play in plays.items():
        by_formation.setdefault(play.get("formation", "(unknown)"), []).append(stem)

    lines: list[str] = []
    lines.append("# Play Catalog")
    lines.append("")
    lines.append("_Generated by `tools/play-catalog/generate.py` — do not edit by hand._")
    lines.append("")
    lines.append(
        f"**{len(base_stems)}** base plays · **{len(mirror_stems)}** mirror plays · "
        f"**{len(families)}** disguise families"
    )
    lines.append("")

    # ── Disguise families ────────────────────────────────────────────────
    lines.append("## Disguise families")
    lines.append("")
    lines.append("Each family is a base play plus companion plays that show the "
                 "defense the same early picture, then diverge.")
    lines.append("")
    for fam in sorted(families, key=lambda f: f["family_id"]):
        lines.append(f"### {fam['family_id']}")
        lines.append(f"- **base:** `{fam['base_play_id']}`")
        comps = fam.get("companion_play_ids") or []
        lines.append(f"- **companions ({len(comps)}):** "
                     + ", ".join(f"`{c}`" for c in comps))
        if fam.get("formation_id"):
            lines.append(f"- formation: `{fam['formation_id']}`")
        lines.append("")

    # ── By formation ─────────────────────────────────────────────────────
    lines.append("## Plays by formation")
    lines.append("")
    for formation in sorted(by_formation):
        stems = sorted(by_formation[formation])
        lines.append(f"### {formation} ({len(stems)} plays)")
        for stem in stems:
            play = plays[stem]
            ptype = play.get("play_type", "?")
            mirror = " (+mirror)" if f"{stem}-left" in mirror_stems else ""
            fams = play_families.get(stem, [])
            fam_note = f" — family: {', '.join(fams)}" if fams else ""
            lines.append(f"- `{stem}` · {ptype}{mirror}{fam_note}")
        lines.append("")

    # ── Un-familied plays ────────────────────────────────────────────────
    unfamilied = sorted(s for s in base_stems if s not in familied)
    lines.append(f"## Un-familied plays ({len(unfamilied)})")
    lines.append("")
    lines.append("Base plays not yet part of any disguise family.")
    lines.append("")
    for stem in unfamilied:
        play = plays[stem]
        lines.append(f"- `{stem}` · {play.get('formation','?')} · {play.get('play_type','?')}")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)} — "
          f"{len(base_stems)} base plays, {len(families)} families, "
          f"{len(unfamilied)} un-familied.")


if __name__ == "__main__":
    main()
